server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
   - url: http://localhost:3100/loki/api/v1/push  # ‚Üê Now localhost works

scrape_configs:
  - job_name: mnp-api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mnp-api
          __path__: /var/log/mnp.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            module: module
            function: funcName
            line: lineno
            message: message
      # - timestamp:
      #     source: timestamp
      #     format: '2006-01-02 15:04:05,000'
      - labels:
          level:
          module:
          function:
      - template:
          source: new_message
          template: '[{{ .module }}:{{ .function }}:{{ .line }}] {{ .message }}'
      - output:
          source: new_message

  - job_name: mnp-payload-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mnp-payload
          __path__: /var/log/payload.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) - (?P<logger>\w+) - (?P<level>\w+) - (?P<message>.+)'
      # - timestamp:
      #     source: timestamp
      #     format: '2006-01-02 15:04:05,000'
      - labels:
          level:
      - output:
          source: message

  # - job_name: docker-all
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: docker-logs
  #         __path__: /var/lib/docker/containers/*/*-json.log
  #   pipeline_stages:
  #     - json:
  #         expressions:
  #           log: log
  #           stream: stream
  #           time: time
  #     # - timestamp:
  #     #     source: time
  #     #     format: RFC3339Nano
  #     - output:
  #         source: log
  #     - labels:
  #         stream:

  - job_name: docker-mnp-api
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      # Only scrape containers with the logging label
      - source_labels: [__meta_docker_container_label_logging]
        regex: "promtail"
        action: keep
      # Set the path to the container log file
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: "/var/lib/docker/containers/$0/*-json.log"
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: log
      - labels:
          stream: